---
sidebar: sidebar
permalink: callhome-dbs-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: callhome.dbs events
---

= callhome.dbs events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== callhome.dbs.cluster.cannot.sync.blocks
*Severity*::
EMERGENCY
*Description*::
This message occurs when the Distributed Block Store (DBS) detects the cluster Block data is in a degraded state, and the auto-heal process to restore full Block data redundancy cannot proceed. Block resources need to be added or restored to the cluster. Too many nodes, Block services, FireStorm services or aggregates may be offline; or possibly the cluster Block services are full. The DBS is responsible for managing the data that backs the FlexVols(R). If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Evaluate the storage capacity of the cluster. If some capacity is currently unavailable due to drives or nodes being offline, attempt the repairs needed to bring them online. Free storage used by FlexVols by deleting unneeded volumes.
*Syslog Message*::
The Distributed Block Store cluster Block data cannot be made fully redundant.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.cluster.capacity.full
*Severity*::
EMERGENCY
*Description*::
This message occurs when the Distributed Block Store (DBS) detects the cluster (or node in the cluster) has completely consumed its capacity. The DBS is responsible for managing the data that backs the FlexVols(R). The cluster data is now read-only. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Evaluate the available capacity of this cluster relative to its usage. If some capacity is currently unavailable due to drives or nodes being offline, attempt the repairs needed to bring them online. Free storage used by FlexVols by deleting unneeded volumes. If the cluster's available capacity appears inconsistent with the calculated expected capacity, then contact NetApp technical support.
*Syslog Message*::
The Distributed Block Store cluster capacity is 100%% full.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.cluster.capacity.nearly.full
*Severity*::
ALERT
*Description*::
This message occurs when the Distributed Block Store (DBS) detects the cluster (or node in the cluster) has consumed nearly all of its capacity. The DBS is responsible for managing the data that backs the FlexVols(R). If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Evaluate the available capacity of this cluster relative to its usage. If some capacity is currently unavailable due to drives or nodes being offline, attempt the repairs needed to bring them online. Free storage used by FlexVols by deleting unneeded volumes.
*Syslog Message*::
The Distributed Block Store cluster capacity is nearly full.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.data.unavailable
*Severity*::
EMERGENCY
*Description*::
This message occurs when some portion of the Distributed Block Store (DBS) data cannot be accessed. The DBS is responsible for managing the data that backs the FlexVols(R). Multiple DBS events that indicate data is unavailable are mapped to this one event. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Contact NetApp technical support for help immediately.
*Syslog Message*::
Call home for %s. The event is \"%s\" of type \"%s\" for Service ID \"%u\" on node \"%u\". Drive ID = %u. Event ID = %u.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*evtMessage* (STRING): Description of the data event, including context details.
*evtType* (STRING): Type of the original DBS event.
*serviceID* (INT): Service ID that identifies the associated DBS service. It will be "0" if there is no associated service.
*nodeID* (INT): Node ID number of the associated node. It will be "0" if there is no associated node.
*driveID* (INT): Drive ID number of the associated drive. It will be "0" if there is no associated drive.
*evtID* (INT): DBS event ID number.
*evtDetails* (STRING): Specific details of the DBS data event. It may be a string, in JSON format, or empty.

== callhome.dbs.generic.cluster.fault
*Severity*::
EMERGENCY
*Description*::
This message occurs when a Distributed Block Store (DBS) emergency cluster fault is reported as a generic fault. The DBS is responsible for managing the data that backs the FlexVols(R). Multiple faults are mapped to this one event. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Contact NetApp technical support for interpretation of this event.
*Syslog Message*::
Call home for %s. The fault is \"%s\" (%u) with severity \"%u\" for Service ID \"%u\" on node \"%u\". Drive list = %s.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*cfCodeName* (STRING): Name of the original DBS cluster fault code.
*cfCode* (INT): DBS cluster fault code number.
*cfSeverity* (INT): Severity of the original DBS cluster fault. This is different than the EMS severity.
*serviceID* (INT): Service ID that identifies the associated cluster service. It will be "0" if there is no associated service.
*nodeID* (INT): Node ID number of the associated node. It will be "0" if there is no associated node.
*cfDriveIDs* (STRING): List of the drive IDs associated with the fault. The list might be empty.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.invalid.block.data
*Severity*::
EMERGENCY
*Description*::
This message occurs when a block stored in the the Distributed Block Store (DBS) has inconsistent data. The cluster is checking the compression, block ID and checksum of the block against expected values. The DBS is responsible for managing the data that backs the FlexVols(R). Multiple DBS events that indicate inconsistent data are mapped to this one event. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Contact NetApp technical support for help immediately.
*Syslog Message*::
Call home for %s. The event is \"%s\" of type \"%s\" for Service ID \"%u\" on node \"%u\". Drive ID = %u. Event ID = %u.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*evtMessage* (STRING): Description of the data event, including context details.
*evtType* (STRING): Type of the original DBS event.
*serviceID* (INT): Service ID that identifies the associated DBS service. It will be "0" if there is no associated service.
*nodeID* (INT): Node ID number of the associated node. It will be "0" if there is no associated node.
*driveID* (INT): Drive ID number of the associated drive. It will be "0" if there is no associated drive.
*evtID* (INT): DBS event ID number.
*evtDetails* (STRING): Specific details of the DBS data event. It may be a string, in JSON format, or empty.

== callhome.dbs.secondary.cache.full
*Severity*::
EMERGENCY
*Description*::
This message occurs when the Distributed Block Store (DBS) detects that Slice volume secondary write cache is full. This is caused when Slice service write requests to the Block service (and by extension the FireStorm service) are not receiving replies. Client write performance may be reduced while this condition exists. The DBS is responsible for managing the data that backs the FlexVols(R). If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Verify that all nodes are online. Verify that all Block and FireStorm services, and associated aggregates, are online. Attempt repairs needed to bring nodes and aggregrates online. If the reason for this condition cannot be found, contact NetApp technical support.
*Syslog Message*::
Call home for %s. Slice volume secondary write cache is full for service ID %u on node %u.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*serviceID* (INT): Service ID that identifies the associated cluster service.
*nodeID* (INT): Node ID number of the associated node.
*cfDriveIDs* (STRING): List of the drive IDs associated with the fault. The list might be empty.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.service.capacity.full
*Severity*::
EMERGENCY
*Description*::
This message occurs when the Distributed Block Store (DBS) detects a service (Slice or Block) that has completely consumed its capacity. The DBS is responsible for managing the data that backs the FlexVols(R). The data for this service is now read-only. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Evaluate the available capacity of this service relative to its usage. If some capacity is currently unavailable due to drives or nodes being offline, attempt the repairs needed to bring them online. Free storage used by FlexVols by deleting unneeded volumes. If the services's available capacity appears inconsistent with the calculated expected capacity, then contact NetApp technical support.
*Syslog Message*::
Call home for %s. The Distributed Block Store capacity is 100%% full for service ID %u on node %u.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*serviceID* (INT): Service ID that identifies the associated cluster service.
*nodeID* (INT): Node ID number of the associated node.
*cfDriveIDs* (STRING): List of the drive IDs associated with the fault. The list might be empty.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).

== callhome.dbs.service.capacity.nearly.full
*Severity*::
ALERT
*Description*::
This message occurs when the Distributed Block Store (DBS) detects a service (Slice or Block) that has consumed nearly all of its capacity. The DBS is responsible for managing the data that backs the FlexVols(R). If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Evaluate the available capacity of this service relative to its usage. If some capacity is currently unavailable due to drives or nodes being offline, attempt the repairs needed to bring them online. Free storage used by FlexVols by deleting unneeded volumes.
*Syslog Message*::
Call home for %s. The Distributed Block Store capacity is nearly full for service ID %u on node %u.
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*serviceID* (INT): Service ID that identifies the associated cluster service.
*nodeID* (INT): Node ID number of the associated node.
*cfDriveIDs* (STRING): List of the drive IDs associated with the fault. The list might be empty.
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
*skip_callhome* (INT): If 1, then the ASUP call home was not executed for this event. Call home is only done for newly reported faults (see cfStatus).
