---
sidebar: sidebar
permalink: dbs-sw-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dbs.sw events
---

= dbs.sw events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== dbs.sw.encr.at.rest
*Severity*::
NOTICE
*Description*::
This message occurs when a Distributed Block Store (DBS) event relating to Software Encryption At Rest occurs, such as master key rekey completes or fails, rewrapping drive keys with new SEAR master key takes too long occur. Software Encryption At Rest when enabled, encrypts all data written, and decrypts all data read automatically in the software. If the original DBS event specifies multiple drives, then an EMS event is generated for each drive.
*Corrective Action*::
None.
*Syslog Message*::
This is a Distributed Block Store Software Encryption At Rest event. The event is \"%s\" of type \"%s\" for Service ID \"%u\" on node \"%u\". Drive ID = %u. Event ID = %u.
*Parameters*::
*evtMessage* (STRING): Description of the DBS event, including context details.
*evtType* (STRING): Type of the original DBS event.
*serviceID* (INT): Service ID that identifies the associated DBS service. It will be "0" if there is no associated service.
*nodeID* (INT): Node ID number of the associated node. It will be "0" if there is no associated node.
*driveID* (INT): Drive ID number of the associated drive. It will be "0" if there is no associated drive.
*evtID* (INT): DBS event ID number.
*evtDetails* (STRING): Specific details of the DBS event. It may be a string, in JSON format, or empty.
