---
sidebar: sidebar
permalink: master-demote-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: master.demote events
---

= master.demote events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== master.demote.cm.committed
*Severity*::
NOTICE
*Description*::
This message occurs when the associated node successfully updated the global database to demote current cluster master. As a result, a new cluster will be promoted.
*Corrective Action*::
(None).
*Syslog Message*::
Service ID "%u" on node ID "%u" successfully updated database to demote cluster master with serviceID "%u" and sequenceNumber "%u".
*Parameters*::
*serviceID* (INT): Service ID that identifies the associated master service.
*nodeID* (INT): Node ID number of the associated node.
*lastKnownLeaderID* (INT): Service ID number of the cluster master last known by this node.
*sequenceNumber* (INT): The sequence number of the cluster master last known by this node.

== master.demote.cm.ex
*Severity*::
NOTICE
*Description*::
This message occurs when the associated node tries to update the global database to demote current cluster master but the operation failed due to an exception. This could happen if another cluster node already made the same database change, or the connection to global database has lost.
*Corrective Action*::
(None).
*Syslog Message*::
Service ID "%u" on node ID "%u" failed to update database to demote cluster master with serviceID "%u" with exception (%s).
*Parameters*::
*serviceID* (INT): Service ID that identifies the associated master service.
*nodeID* (INT): Node ID number of the associated node.
*lastKnownLeaderID* (INT): Service ID number of the cluster master last known by this node.
*exceptionCode* (STRING): The exception code.
